### ISSUE TITLE
CSRF token error

### ISSUE THREAD

**Issue by clabnet** [jagr-co/adonisjs-bouncer#1]
Hi, 
thank you for this code.

I'm trying to learn Bouncer, but I have this error using Postman login API :
```
E_BAD_CSRF_TOKEN: Invalid CSRF Token
```

**Comment by tomgobich** [comment]
Hi! This project is set up as a monolithic project, so it's making use of CSRF tokens and fields. In order to use Postman, you'll either want to grab the request's current CSRF token from a field on the page and provide the `_csrf` field with the token value in the body on your Postman request. Or, you can grab the `XSRF-TOKEN` value from the cookies and provide that as an `X-XSRF-TOKEN` header. These two approaches can be burdensome though, since the token is request specific.

Alternatively, you can turn CSRF off for the project by setting the enabled flag for CSRF to false within the `config/shield.ts` file (line 77).

You can read more about CSRF protection within AdonisJS here:
https://docs.adonisjs.com/guides/security/web-security#csrf-protection
